### ISSUE TITLE
GAMEOBJECT_TYPE_GOOBER bug

### ISSUE THREAD

**Issue by Mysterium** [cooler-SAI/JadeCore#22]
Something is wrong with this type of gameobject, even "unknown spell id 130231 at use action for gameobject <Entry: 215133 GoType: 10>"
I think it's important because there are many quests involving this type of GO.
For example http://www.wowhead.com/object=215133, http://www.wowhead.com/object=186565.

**Comment by cybrann** [comment]
If you could give more proper explanation of this bug, then it might be possible to fix it.

**Comment by Mysterium** [comment]
In the quest http://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough
You need to click on the handwrap, but nothing happens

**Comment by cooler-SAI** [comment]
@Mysterium , where are your commits?

**Comment by Mysterium** [comment]
Yeah, i have troubles with commits, cant send them to github, but i dont know why, no errors, im so sry :/

**Comment by cybrann** [comment]
@Mysterium if you want send me all commits you have on skype and I'll add them.

My skype is: sko.du
