### ISSUE TITLE
Updating the core

### ISSUE THREAD

**Issue by cybrann** [cooler-SAI/JadeCore#23]
@cooler-SAI We need to update our opcodes and dbc structure to 5.4.8 because it is impossible to get opcodes for 5.4.7 version and 5.4.8 still has some hope. We are missing opcodes for a lot of stuff loke scenarios, raid finder, flexibile raid, wargames and battle pets.

**Comment by cooler-SAI** [comment]
Agreed,but we looose only this opcodes?do you have it for548? Coz skyfire don't have all I think and it's impossible get them now

**Comment by cybrann** [comment]
It's possible from wowfreakz private server I think. They have all that stuff working. And also I have mos of the opcoses alredy, but it will take tim to update
