### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by darkmord1991** [cooler-SAI/JadeCore#46]
Hello guys,

as Dusko told me in Skype I should open an issue for my question.
I want to ask if you need a test server for your Project?

I would give you database access and I am able to compile every evening here from germany and change the core in that time. 
The server has 8 cores, 16gb ram and 1gbit connection. Its an dedicated host hosted in france from ovh.

so please be free to contact me in skype with Darkmord1991.

best regards
Darkmord1991

**Comment by cybrann** [comment]
When I'm scripting bosses I need to recompile multiply times in 5-6 minutes and I can pretty much test anything on my pc. I told you to post here to cbeck if there is someone else who wants to use this

**Comment by cooler-SAI** [comment]
I think it's useless, but thanks anyway
